spring.application.name=movie-platform

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.mvc.hiddenmethod.filter.enabled=true

spring.profiles.active=local

# ? ???? 0? ?? 1? ??
spring.data.web.pageable.one-indexed-parameters=true

spring.data.web.pageable.default-page-size=20